<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows8.0</TargetFramework> <!-- 버전은 다를 수 있음 -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>True</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\lssLib.Config\lssLib.Config.csproj" />
  </ItemGroup>

</Project>