<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Core\" />
		<Folder Include="Detectors\" />
		<Folder Include="Core\" />
		<Folder Include="ViewModels\" />
		<Folder Include="Views\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\..\..\Base\BCL\Config\lssLib.Config\lssLib.Config.csproj" />
	  <ProjectReference Include="..\..\..\..\..\Base\BCL\DB\lssLib.DB.Sqlite\lssLib.DB.Sqlite.csproj" />
	  <ProjectReference Include="..\..\..\..\..\Base\BCL\DB\lssLib.DB\lssLib.DB.csproj" />
	  <ProjectReference Include="..\..\..\..\..\Base\BCL\log\lssLib.Log\lssLib.Log.csproj" />
	  <ProjectReference Include="..\..\..\..\..\Base\BCL\Message\lssLib.Messaging\lssLib.Messaging.csproj" />
	  <ProjectReference Include="..\..\..\..\..\Base\BCL\Utils\lssLib.Utils\lssLib.Utils.csproj" />
	  <ProjectReference Include="..\..\Themes\IIoT.UI.Themes\IIoT.UI.Themes.csproj" />
	</ItemGroup>
	
</Project>
