<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<!-- lssLib.DB Core 참조 -->
	<ItemGroup>
		<ProjectReference Include="..\lssLib.DB\lssLib.DB.csproj" />
	</ItemGroup>

	<!-- InfluxDB 공식 클라이언트 -->
	<ItemGroup>
		<PackageReference Include="InfluxDB.Client" Version="5.*" />
	</ItemGroup>
</Project>
