<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
	<Description>lssLib.Net Base — 인터페이스 · 추상 클래스 · 핵심 열거형 · 인프라</Description>
	<SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
  </PropertyGroup>
</Project>
